/**
 * CCCC SDK - TypeScript Client for CCCC Daemon (IPC v1)
 */

import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const pkg = require('../package.json') as { version?: string };

// Export client class.
export { CCCCClient } from './client.js';

// Export error classes and codes.
export {
  CCCCSDKError,
  DaemonAPIError,
  DaemonConnectionError,
  DaemonUnavailableError,
  IncompatibleDaemonError,
  OutcomeUnknownError,
  RequestTooLargeError,
  ErrorCodes,
} from './errors.js';
export type { ErrorCode } from './errors.js';

// Export transport utility functions and constants.
export {
  discoverEndpoint,
  defaultHome,
  MAX_LINE_SIZE,
  MAX_REQUEST_SIZE,
  DEFAULT_TIMEOUT_MS,
} from './transport.js';

// Export type guards.
export {
  isChatMessageEvent,
  isMailReadEvent,
  isChatCrossGroupReceiptEvent,
  isStreamEvent,
  isStreamHeartbeat,
} from './types.js';

// Export all types.
export type {
  // Core types.
  DaemonEndpoint,
  DaemonRequest,
  DaemonResponse,
  DaemonErrorPayload,
  AddressDescriptor,
  // Event types.
  EventStreamEvent,
  EventStreamHeartbeat,
  EventStreamUnknown,
  EventStreamItem,
  CCCSEvent,
  // Client options.
  CCCCClientOptions,
  CompatibilityOptions,
  // Message types (shared).
  MessageRef,
  MessageAttachment,
  MessageMode,
  ReplyMessageMode,
  MessageHistoryOptions,
  AsyncResultEnvelope,
  // Operation argument types.
  SendOptions,
  SendFilesOptions,
  TrackedSendOptions,
  SendCrossGroupOptions,
  ReplyOptions,
  TaskListOptions,
  ActorAddOptions,
  ActorUpdateOptions,
  GroupResetOptions,
  GroupPreambleSetOptions,
  GroupPreambleResetOptions,
  ActorEnvPrivateUpdateOptions,
  ActorInternalKind,
  ActorRuntimeStateSource,
  AgentRuntime,
  ActorProfile,
  ActorProfileCapabilityDefaults,
  ActorProfileUsage,
  ActorProfileUpsertOptions,
  ActorProfileSecretUpdateOptions,
  ActorProfileSecretCopyFromActorOptions,
  ActorProfileSecretCopyFromProfileOptions,
  HeadlessStatus,
  HeadlessStatusOptions,
  HeadlessSetStatusOptions,
  GroupCreateOptions,
  GroupUpdateOptions,
  GroupCopyExportOptions,
  RemoteAccessOptions,
  RemoteAccessConfigureOptions,
  GroupCopyPackageInput,
  GroupCopyPreviewImportOptions,
  GroupCopyImportOptions,
  GroupDetachScopeOptions,
  CapabilityOverviewOptions,
  CapabilitySearchOptions,
  CapabilityEnableOptions,
  CapabilityBlockOptions,
  CapabilityStateOptions,
  CapabilityAllowlistMode,
  CapabilityAllowlistGetOptions,
  CapabilityAllowlistValidateOptions,
  CapabilityAllowlistUpdateOptions,
  CapabilityAllowlistResetOptions,
  CapabilityImportOptions,
  CapabilityUninstallOptions,
  CapabilityToolCallOptions,
  CapabilityVisibilityOptions,
  CapabilityInstallTargetOptions,
  CapabilitySourceDeleteOptions,
  GroupSpaceProvider,
  GroupSpaceLane,
  GroupSpaceStatusOptions,
  GroupSpaceSpacesOptions,
  GroupSpaceCapabilitiesOptions,
  GroupSpaceBindOptions,
  GroupSpaceIngestOptions,
  GroupSpaceQueryOptions,
  GroupSpaceSourcesOptions,
  GroupSpaceArtifactOptions,
  GroupSpaceJobsOptions,
  GroupSpaceSyncOptions,
  GroupSpaceProviderCredentialStatusOptions,
  GroupSpaceProviderCredentialUpdateOptions,
  GroupSpaceProviderHealthCheckOptions,
  GroupSpaceProviderAuthOptions,
  PresentationCardType,
  PresentationTableData,
  PresentationGetOptions,
  PresentationPublishOptions,
  PresentationClearOptions,
  PresentationBrowserOpenOptions,
  PresentationBrowserInfoOptions,
  PresentationBrowserCloseOptions,
  AssistantLifecycle,
  AssistantId,
  AssistantStateOptions,
  AssistantVoiceRecordingLeaseAction,
  AssistantVoiceRecordingLeaseOptions,
  AssistantSettingsUpdateOptions,
  AssistantStatusUpdateOptions,
  ObservabilityUpdateOptions,
  BrandingUpdateOptions,
  DebugSnapshotOptions,
  DebugTailLogsOptions,
  DebugClearLogsOptions,
  TerminalTailOptions,
  TerminalHistoryOptions,
  TerminalSinceOptions,
  TerminalSnapshotOptions,
  TerminalClearOptions,
  WebModelRuntimeWaitNextTurnOptions,
  WebModelRuntimeCompletionStatus,
  WebModelRuntimeCompleteTurnOptions,
  WebModelDeliveryMode,
  WebModelDeliveryPreferencesGetOptions,
  WebModelDeliveryPreferencesUpdateOptions,
  WebModelRuntimeRecoverTurnOptions,
  LedgerSnapshotOptions,
  LedgerCompactOptions,
  StreamEmitOptions,
  SystemNotifyOptions,
  RegistryReconcileOptions,
  RuntimeHermesPrepareOptions,
  RuntimeHermesMcpTestOptions,
  AutomationNotifyPriority,
  AutomationTriggerInterval,
  AutomationTriggerCron,
  AutomationTriggerAt,
  AutomationTrigger,
  AutomationActionNotify,
  AutomationActionGroupState,
  AutomationActionActorControl,
  AutomationAction,
  AutomationRule,
  AutomationRuleSet,
  AutomationManageCreateRule,
  AutomationManageUpdateRule,
  AutomationManageSetRuleEnabled,
  AutomationManageDeleteRule,
  AutomationManageReplaceAllRules,
  AutomationManageAction,
  GroupAutomationUpdateOptions,
  GroupAutomationManageOptions,
  GroupAutomationResetBaselineOptions,
  InboxOptions,
  MessageDeliverOptions,
  ReplyRequestCancelOptions,
  ContextSyncOptions,
  CoordinationBriefUpdateOptions,
  CoordinationNoteAddOptions,
  TaskCreateOptions,
  TaskUpdateOptions,
  TaskMoveOptions,
  TaskRestoreOptions,
  TaskDeleteOptions,
  AgentStateUpdateOptions,
  AgentStateClearOptions,
  MetaMergeOptions,
  EventsStreamOptions,
  CapabilityUseOptions,
  MemorySearchOptions,
  MemoryGetOptions,
  MemoryWriteOptions,
  MemoryHealthOptions,
  MemoryProfileGetOptions,
  MemoryRemeMessage,
  MemoryRemeLayoutGetOptions,
  MemoryRemeIndexSyncOptions,
  MemoryRemeSearchOptions,
  MemoryRemeGetOptions,
  MemoryRemeContextCheckOptions,
  MemoryRemeCompactOptions,
  MemoryRemeDedupIntent,
  MemoryRemeDailyFlushOptions,
  MemoryRemeWriteOptions,
  // Result types.
  SendResult,
  SendAndWaitOptions,
  // Strongly-typed event data.
  ChatMessageEventData,
  MailReadEventData,
  ChatCrossGroupReceiptEventData,
  NotifyReminderEventData,
  ChatMessageEvent,
  MailReadEvent,
  ChatCrossGroupReceiptEvent,
  // B6: Strongly-typed result types.
  ActorInfo,
  ScopeInfo,
  GroupInfo,
  PingResult,
  GroupsResult,
  GroupShowResult,
  GroupCreateResult,
  ActorListResult,
  ActorAddResult,
  InboxPeekResult,
  InboxReadResult,
  MessageHistoryResult,
  TerminalSnapshotResult,
  WebModelDeliveryPreferencesResult,
  WebModelRuntimeRecoverTurnResult,
  ContextGetResult,
  ContextDetail,
} from './types.js';

/** SDK version */
export const version = String(pkg.version || '0.0.0');
